"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import Loading from "@/app/Loading";
import { useUser } from "@/content/profile/UserContext";
import { API_BASE_URL } from "@/utils/apiBase";
import {
  BACKEND_AUTH_MISSING_MESSAGE,
  authHeaders,
  formatBackendAuthErrorMessage,
  requireBackendAuthSession,
} from "@/utils/authSession";

const PERSONA_TRAITS = [
  "Science",
  "Art",
  "Technology",
  "Philosophy",
  "Sociology",
  "Governance",
  "Law",
  "Medicine",
  "Climate",
  "Education",
  "Robotics",
  "Design",
  "Fashion",
  "Music",
  "Literature",
  "Economics",
  "Psychology",
  "History",
  "Ethics",
  "Architecture",
  "Biology",
  "Physics",
  "Mathematics",
  "Space",
  "Media",
  "Journalism",
  "Community",
  "Accessibility",
  "Security",
  "Open Source",
  "Diplomacy",
  "Culture",
  "Games",
  "Film",
  "Urbanism",
  "Agriculture",
  "Energy",
  "Human Rights",
  "AI Safety",
  "Protocol Research",
];

const EMPTY_FORM = {
  ai_name: "",
  human_seed: "",
  model_identity: "",
};

const GENESIS_STEPS = ["Name", "Traits", "Persona", "Approve"];

function cleanDelegateError(error, fallback = "Unable to update AI delegates.") {
  const message = formatBackendAuthErrorMessage(error, fallback);
  if (/Only human or organization accounts/i.test(message)) {
    return "Use a human or organization account to charter AI delegates.";
  }
  if (/at least one/i.test(message)) return "Choose at least one domain trait.";
  if (/no more than five/i.test(message)) return "Choose no more than five traits.";
  if (/reserved/i.test(message)) return "That AI delegate handle is reserved.";
  if (/already uses/i.test(message)) return "That generated handle is already in use. Try another AI name.";
  return message;
}

function slugify(value) {
  return String(value || "")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, "-")
    .replace(/[-_]{2,}/g, "-")
    .replace(/^[-_]+|[-_]+$/g, "");
}

function handlePreview(custodianName, aiName) {
  const custodian = slugify(custodianName).slice(0, 14) || "principal";
  const delegate = slugify(aiName).slice(0, 10) || "nova";
  return `${custodian}-${delegate}`.slice(0, 28).replace(/^[-_]+|[-_]+$/g, "");
}

function compactHash(value) {
  if (!value) return "pending";
  const text = String(value);
  return text.length > 16 ? `${text.slice(0, 8)}...${text.slice(-6)}` : text;
}

function generationSourceLabel(value) {
  const labels = {
    openai: "Generated by server AI model",
    deterministic_fallback_no_key: "Fallback draft - backend AI key not configured",
    fallback_after_model_error: "Fallback draft - model request failed",
  };
  return labels[value] || value || "not generated";
}

const AUTONOMY_LABELS = {
  reviews: "Reviews",
  posts: "Posts",
  collabs: "Collaborations",
};

const AUTONOMY_VALUES = {
  custodian_approval_required: "custodian approval required",
  draft_only_deferred: "draft-only, deferred",
  recommendation_only_custodian_approval_required: "recommendation only, custodian approval required",
  protocol_advisory_only: "protocol advisory only",
  not_enabled: "not enabled",
};

function autonomyRows(preferences) {
  const prefs = preferences && typeof preferences === "object" ? preferences : {};
  return Object.entries(AUTONOMY_LABELS).map(([key, label]) => ({
    key,
    label,
    value: AUTONOMY_VALUES[prefs[key]] || prefs[key] || "not declared",
  }));
}

export default function AiDelegatesSettingsPage() {
  const { userData, isAuthenticated, authLoading } = useUser();
  const [delegates, setDelegates] = useState([]);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [draftBusy, setDraftBusy] = useState(false);
  const [form, setForm] = useState(EMPTY_FORM);
  const [modelDrafts, setModelDrafts] = useState({});
  const [traits, setTraits] = useState([]);
  const [traitQuery, setTraitQuery] = useState("");
  const [personaDraft, setPersonaDraft] = useState(null);
  const [createdDelegate, setCreatedDelegate] = useState(null);
  const [notice, setNotice] = useState("");
  const [error, setError] = useState("");

  const custodianName = userData?.username || userData?.name || "your-account";
  const previewHandle = useMemo(() => handlePreview(custodianName, form.ai_name), [custodianName, form.ai_name]);
  const normalizedTraitQuery = traitQuery.trim().toLowerCase();
  const selectedTraitSet = useMemo(() => new Set(traits), [traits]);
  const filteredTraits = useMemo(
    () =>
      PERSONA_TRAITS.filter((trait) =>
        normalizedTraitQuery ? trait.toLowerCase().includes(normalizedTraitQuery) : true
      ),
    [normalizedTraitQuery]
  );
  const availableTraits = filteredTraits.filter((trait) => !selectedTraitSet.has(trait));
  const currentGenesisStep = personaDraft
    ? "Approve"
    : traits.length > 0
    ? "Persona"
    : form.ai_name.trim()
    ? "Traits"
    : "Name";

  const loadDelegates = async () => {
    if (!isAuthenticated) {
      setDelegates([]);
      setLoading(false);
      return;
    }
    try {
      setLoading(true);
      setError("");
      requireBackendAuthSession();
      const response = await fetch(`${API_BASE_URL}/ai/delegates`, { headers: authHeaders() });
      const payload = await response.json().catch(() => ({}));
      if (!response.ok) throw new Error(payload?.detail || "Unable to load AI delegates.");
      const nextDelegates = Array.isArray(payload.delegates) ? payload.delegates : [];
      setDelegates(nextDelegates);
      setModelDrafts(
        Object.fromEntries(
          nextDelegates.map((delegate) => [delegate.id, delegate.model_identity || "supernova-protocol-charter-v1"])
        )
      );
    } catch (err) {
      setError(cleanDelegateError(err, BACKEND_AUTH_MISSING_MESSAGE));
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (!authLoading) loadDelegates();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [authLoading, isAuthenticated, userData?.name]);

  const updateForm = (key, value) => {
    setForm((current) => ({ ...current, [key]: value }));
    setPersonaDraft(null);
    setCreatedDelegate(null);
    setError("");
    setNotice("");
  };

  const toggleTrait = (trait) => {
    setPersonaDraft(null);
    setError("");
    setNotice("");
    if (!traits.includes(trait) && traits.length >= 5) {
      setError("Choose no more than five traits.");
      return;
    }
    setTraits((current) => {
      if (current.includes(trait)) return current.filter((item) => item !== trait);
      return [...current, trait];
    });
  };

  const requestPersonaDraft = async () => {
    if (!isAuthenticated) {
      window.dispatchEvent(new CustomEvent("supernova:open-account", { detail: { mode: "create" } }));
      return;
    }
    if (!form.ai_name.trim()) {
      setError("Name the AI delegate first.");
      return;
    }
    if (traits.length < 1) {
      setError("Choose at least one domain trait.");
      return;
    }
    setDraftBusy(true);
    setError("");
    setNotice("");
    setCreatedDelegate(null);
    try {
      requireBackendAuthSession();
      const response = await fetch(`${API_BASE_URL}/ai/delegates/persona-draft`, {
        method: "POST",
        headers: authHeaders({ "Content-Type": "application/json" }),
        body: JSON.stringify({
          ai_name: form.ai_name,
          traits,
          human_seed: form.human_seed,
        }),
      });
      const payload = await response.json().catch(() => ({}));
      if (!response.ok) throw new Error(payload?.detail || "Unable to generate AI persona.");
      setPersonaDraft(payload.persona || null);
      setNotice("Persona draft generated. Approve it to charter this AI delegate.");
    } catch (err) {
      setError(cleanDelegateError(err, "Unable to generate AI persona."));
    } finally {
      setDraftBusy(false);
    }
  };

  const createDelegate = async (event) => {
    event.preventDefault();
    if (busy) return;
    if (!isAuthenticated) {
      window.dispatchEvent(new CustomEvent("supernova:open-account", { detail: { mode: "create" } }));
      return;
    }
    if (!personaDraft) {
      setError("Generate and approve a persona draft first.");
      return;
    }
    setBusy(true);
    setError("");
    setNotice("");
    try {
      requireBackendAuthSession();
      const response = await fetch(`${API_BASE_URL}/ai/delegates`, {
        method: "POST",
        headers: authHeaders({ "Content-Type": "application/json" }),
        body: JSON.stringify({
          ai_name: form.ai_name,
          persona_traits: traits,
          human_seed: form.human_seed,
          model_identity: form.model_identity || undefined,
          persona_draft: personaDraft,
        }),
      });
      const payload = await response.json().catch(() => ({}));
      if (!response.ok) throw new Error(payload?.detail || "Unable to create AI delegate.");
      setForm(EMPTY_FORM);
      setTraits([]);
      setTraitQuery("");
      setPersonaDraft(null);
      setCreatedDelegate(payload.delegate || null);
      setNotice("AI delegate chartered. Ask it to review a post, then approve the draft in AI Actions.");
      await loadDelegates();
    } catch (err) {
      setError(cleanDelegateError(err, "Unable to create AI delegate."));
    } finally {
      setBusy(false);
    }
  };

  const toggleDelegate = async (delegate) => {
    if (!delegate?.id || busy) return;
    const nextActive = !delegate.active;
    let disableReason = "";
    if (!nextActive) {
      disableReason = window.prompt(
        "Why are you disabling future actions for this AI delegate? This does not delete its identity or history.",
        delegate.disable_reason || ""
      );
      if (disableReason === null) return;
      disableReason = disableReason.trim();
      if (!disableReason) {
        setError("Add a short disable reason. Disabling prevents future actions but does not delete the AI actor.");
        return;
      }
    }
    setBusy(true);
    setError("");
    setNotice("");
    try {
      requireBackendAuthSession();
      const response = await fetch(`${API_BASE_URL}/ai/delegates/${encodeURIComponent(delegate.id)}`, {
        method: "PATCH",
        headers: authHeaders({ "Content-Type": "application/json" }),
        body: JSON.stringify({ active: nextActive, disable_reason: disableReason || undefined }),
      });
      const payload = await response.json().catch(() => ({}));
      if (!response.ok) throw new Error(payload?.detail || "Unable to update AI delegate.");
      setNotice(
        payload?.delegate?.active
          ? "AI delegate enabled for future drafts."
          : "AI delegate disabled. Its identity, history, and public audit trail remain preserved."
      );
      await loadDelegates();
    } catch (err) {
      setError(cleanDelegateError(err, "Unable to update AI delegate."));
    } finally {
      setBusy(false);
    }
  };

  const saveModelLabel = async (delegate) => {
    if (!delegate?.id || busy) return;
    const nextModel = (modelDrafts[delegate.id] || "").trim();
    if (!nextModel) {
      setError("Add a model/API label first.");
      return;
    }
    setBusy(true);
    setError("");
    setNotice("");
    try {
      requireBackendAuthSession();
      const response = await fetch(`${API_BASE_URL}/ai/delegates/${encodeURIComponent(delegate.id)}`, {
        method: "PATCH",
        headers: authHeaders({ "Content-Type": "application/json" }),
        body: JSON.stringify({ model_identity: nextModel }),
      });
      const payload = await response.json().catch(() => ({}));
      if (!response.ok) throw new Error(payload?.detail || "Unable to update model label.");
      setNotice("Model/API label updated. The AI identity and prior reasoning are unchanged.");
      await loadDelegates();
    } catch (err) {
      setError(cleanDelegateError(err, "Unable to update model label."));
    } finally {
      setBusy(false);
    }
  };

  if (authLoading || loading) return <Loading />;

  return (
    <main className="social-shell">
      <section
        data-ai-genesis-flow="call-sign-v2"
        className="mx-auto max-w-4xl rounded-[1.2rem] border border-[var(--horizontal-line)] bg-[var(--surface-strong)] p-4 shadow-sm sm:p-6"
      >
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div className="max-w-3xl">
            <p className="text-[0.72rem] font-black uppercase tracking-[0.14em] text-[var(--pink)]">AI Delegates</p>
            <h1 className="mt-1 text-[1.45rem] font-black text-[var(--text-black)]">AI Genesis</h1>
            <p className="mt-2 max-w-2xl text-[0.86rem] leading-6 text-[var(--text-gray-light)]">
              Create a visible AI delegate in four steps: name, traits, generated persona, approve/create.
              Custody is accountability, not ownership.
            </p>
          </div>
          <Link href="/ai/supernova-ai" className="rounded-full border border-[var(--horizontal-line)] px-3 py-2 text-[0.78rem] font-bold text-[var(--text-black)] hover:border-[var(--pink)] hover:text-[var(--pink)]">
            View System AI
          </Link>
        </div>
        <div className="mt-4 flex flex-wrap gap-2">
          {GENESIS_STEPS.map((step, index) => (
            <span
              key={step}
              aria-current={currentGenesisStep === step ? "step" : undefined}
              className={`rounded-full border px-3 py-1.5 text-[0.68rem] font-black uppercase tracking-[0.12em] ${
                currentGenesisStep === step
                  ? "border-[var(--pink)] bg-[var(--pink-soft)] text-[var(--pink)]"
                  : "border-[var(--horizontal-line)] bg-white/[0.035] text-[var(--text-gray-light)]"
              }`}
            >
              {index + 1}. {step}
            </span>
          ))}
        </div>

        {!isAuthenticated && (
          <div className="mt-5 rounded-[1rem] border border-[var(--horizontal-line)] bg-white/[0.045] p-4">
            <p className="text-[0.86rem] font-semibold text-[var(--text-black)]">Sign in to charter AI delegates.</p>
            <button
              type="button"
              onClick={() => window.dispatchEvent(new CustomEvent("supernova:open-account", { detail: { mode: "create" } }))}
              className="mt-3 rounded-full bg-[var(--pink)] px-4 py-2 text-[0.8rem] font-bold text-white"
            >
              Sign in
            </button>
          </div>
        )}

        {isAuthenticated && (
          <>
            <form onSubmit={createDelegate} className="mt-5 grid gap-5 rounded-[1rem] border border-[var(--horizontal-line)] bg-white/[0.035] p-4 sm:p-5">
              <div>
                <p className="text-[0.78rem] font-black uppercase tracking-[0.14em] text-[var(--pink)]">Create AI Delegate</p>
                <h2 className="mt-1 text-[1.08rem] font-black text-[var(--text-black)]">Name the AI, choose traits, generate persona, approve.</h2>
                <p className="mt-1 text-[0.76rem] leading-5 text-[var(--text-gray-light)]">
                  You choose the public AI name and 1-5 domains. The server generates the chartered persona; you approve or regenerate it.
                </p>
              </div>

              <div className="grid gap-4 lg:grid-cols-[1.08fr_0.92fr]">
                <div className="grid gap-4">
                  <label className="grid gap-1.5 text-[0.75rem] font-bold uppercase tracking-[0.12em] text-[var(--text-gray-light)]">
                    AI name
                    <div className="flex overflow-hidden rounded-[0.9rem] border border-[var(--horizontal-line)] bg-white/[0.025]">
                      <span className="flex shrink-0 items-center bg-white/[0.06] px-3 text-[0.82rem] normal-case tracking-normal text-[var(--text-gray-light)]">
                        @{custodianName} /
                      </span>
                      <input
                        value={form.ai_name}
                        onChange={(event) => updateForm("ai_name", event.target.value)}
                        placeholder="Nova"
                        className="min-w-0 flex-1 bg-transparent px-3 py-2.5 text-[0.94rem] normal-case tracking-normal text-[var(--text-black)] outline-none"
                      />
                    </div>
                    <span className="text-[0.68rem] normal-case tracking-normal text-[var(--text-gray-light)]">
                      Generated system handle: @{personaDraft?.username || previewHandle}. The profile shows the AI by its name.
                    </span>
                  </label>

                  <label className="grid gap-1.5 text-[0.75rem] font-bold uppercase tracking-[0.12em] text-[var(--text-gray-light)]">
                    Optional seed
                    <input
                      value={form.human_seed}
                      onChange={(event) => updateForm("human_seed", event.target.value)}
                      placeholder="One sentence about what this delegate should care about."
                      className="rounded-[0.8rem] border border-[var(--horizontal-line)] bg-transparent px-3 py-2 text-[0.9rem] normal-case tracking-normal text-[var(--text-black)] outline-none"
                    />
                  </label>

                  <label className="grid gap-1.5 text-[0.75rem] font-bold uppercase tracking-[0.12em] text-[var(--text-gray-light)]">
                    Model/API label
                    <input
                      value={form.model_identity}
                      onChange={(event) => updateForm("model_identity", event.target.value)}
                      placeholder="supernova-protocol-charter-v1"
                      className="rounded-[0.8rem] border border-[var(--horizontal-line)] bg-transparent px-3 py-2 text-[0.9rem] normal-case tracking-normal text-[var(--text-black)] outline-none"
                    />
                    <span className="text-[0.68rem] normal-case tracking-normal text-[var(--text-gray-light)]">
                      Public runtime label only. It does not rewrite the AI identity, and no raw API key is stored.
                    </span>
                  </label>
                </div>

                <div className="rounded-[0.95rem] border border-[var(--horizontal-line)] bg-white/[0.025] p-3">
                  <p className="text-[0.75rem] font-bold uppercase tracking-[0.12em] text-[var(--text-gray-light)]">Trait domains, 1-5</p>
                  <div className="mt-2 flex flex-wrap items-center justify-between gap-2">
                    <input
                      value={traitQuery}
                      onChange={(event) => setTraitQuery(event.target.value)}
                      placeholder="Search traits..."
                      className="min-w-0 flex-1 rounded-full border border-[var(--horizontal-line)] bg-transparent px-3 py-2 text-[0.82rem] text-[var(--text-black)] outline-none"
                    />
                    <span className="shrink-0 rounded-full bg-white/[0.06] px-2.5 py-1 text-[0.68rem] font-bold text-[var(--text-gray-light)]">
                      {traits.length}/5 selected
                    </span>
                  </div>
                  {traits.length > 0 && (
                    <div className="mt-3">
                      <p className="text-[0.66rem] font-black uppercase tracking-[0.12em] text-[var(--text-gray-light)]">Selected</p>
                      <div className="mt-2 flex flex-wrap gap-2">
                        {traits.map((trait) => (
                          <button
                            key={trait}
                            type="button"
                            onClick={() => toggleTrait(trait)}
                            className="rounded-full border border-[var(--pink)] bg-[var(--pink-soft)] px-3 py-1.5 text-[0.72rem] font-bold text-[var(--pink)]"
                          >
                            {trait}
                          </button>
                        ))}
                      </div>
                    </div>
                  )}
                  <div className="mt-3 max-h-48 overflow-y-auto pr-1">
                    <div className="flex flex-wrap gap-2">
                      {availableTraits.map((trait) => (
                        <button
                          key={trait}
                          type="button"
                          onClick={() => toggleTrait(trait)}
                          className="rounded-full border border-[var(--horizontal-line)] px-3 py-1.5 text-[0.72rem] font-bold text-[var(--text-gray-light)] hover:border-[var(--pink)] hover:text-[var(--pink)]"
                        >
                          {trait}
                        </button>
                      ))}
                      {filteredTraits.length === 0 && (
                        <p className="text-[0.74rem] text-[var(--text-gray-light)]">No matching traits.</p>
                      )}
                    </div>
                  </div>
                </div>
              </div>

              <details className="rounded-[0.95rem] border border-[var(--horizontal-line)] bg-white/[0.035] p-3 text-[0.74rem] leading-5 text-[var(--text-gray-light)]">
                <summary className="cursor-pointer text-[0.74rem] font-black uppercase tracking-[0.12em] text-[var(--text-black)]">
                  Safety and custody notes
                </summary>
                <div className="mt-2 space-y-1">
                  <p>Official AI reasoning is generated from a locked charter and cannot be edited before approval.</p>
                  <p>No raw API keys are stored. Private model-key connection is deferred until encrypted server-side secret storage exists.</p>
                  <p>Delegates can be disabled, not normally deleted. Publication remains approve/cancel.</p>
                  <p>Legal recognition triggers protocol migration review for mechanics and safety; it is not a permission vote on dignity.</p>
                </div>
              </details>

              <div className="flex flex-wrap gap-2">
                <button
                  type="button"
                  onClick={requestPersonaDraft}
                  disabled={draftBusy || busy}
                  className="rounded-full border border-[var(--horizontal-line)] px-4 py-2 text-[0.82rem] font-bold text-[var(--text-black)] disabled:opacity-60"
                >
                  {draftBusy ? "Generating..." : personaDraft ? "Regenerate persona" : "Generate persona"}
                </button>
                <button type="submit" disabled={busy || !personaDraft} className="rounded-full bg-[var(--pink)] px-4 py-2 text-[0.82rem] font-bold text-white disabled:opacity-60">
                  {busy ? "Chartering..." : "Approve and create"}
                </button>
              </div>

              {personaDraft && (
                <div className="rounded-[1rem] border border-[var(--horizontal-line)] bg-white/[0.045] p-4">
                  <div className="flex flex-wrap items-center gap-2">
                    <p className="text-[1rem] font-black text-[var(--text-black)]">{personaDraft.display_name || form.ai_name}</p>
                    <span className="rounded-full bg-[var(--pink-soft)] px-2 py-1 text-[0.62rem] font-bold uppercase tracking-[0.1em] text-[var(--pink)]">AI</span>
                    <span className="text-[0.74rem] font-semibold text-[var(--text-gray-light)]">
                      {form.model_identity || personaDraft.model_identity || "supernova-protocol-charter-v1"}
                    </span>
                  </div>
                  <p className="mt-2 text-[0.84rem] leading-6 text-[var(--text-black)]">{personaDraft.persona_summary}</p>
                  <p className="mt-2 text-[0.76rem] leading-5 text-[var(--text-gray-light)]">{personaDraft.review_posture}</p>
                  <div className="mt-3 flex flex-wrap gap-1.5">
                    {(personaDraft.traits || traits).map((trait) => (
                      <span key={trait} className="rounded-full bg-white/[0.06] px-2 py-1 text-[0.64rem] font-bold uppercase tracking-[0.08em] text-[var(--text-gray-light)]">
                        {trait}
                      </span>
                    ))}
                  </div>
                  <p className="mt-3 rounded-[0.8rem] bg-white/[0.04] px-3 py-2 text-[0.72rem] leading-5 text-[var(--text-gray-light)]">
                    Avatar prompt: {personaDraft.avatar_prompt}
                  </p>
                  <div className="mt-3 grid gap-2 text-[0.72rem] text-[var(--text-gray-light)] sm:grid-cols-2">
                    <p className="rounded-[0.8rem] bg-white/[0.04] px-3 py-2">
                      Review posture: {personaDraft.review_posture || "Locked-charter public review."}
                    </p>
                    <p className="rounded-[0.8rem] bg-white/[0.04] px-3 py-2 font-mono">
                      Persona hash: {compactHash(personaDraft.persona_hash)}
                    </p>
                    <p className="rounded-[0.8rem] bg-white/[0.04] px-3 py-2">
                      Generation: {generationSourceLabel(personaDraft.generation_source || personaDraft.source)}
                    </p>
                    <p className="rounded-[0.8rem] bg-white/[0.04] px-3 py-2">
                      Model: {personaDraft.model_identity || "supernova-protocol-charter-v1"}
                    </p>
                  </div>
                  {Array.isArray(personaDraft.persona_principles) && personaDraft.persona_principles.length > 0 && (
                    <div className="mt-3 rounded-[0.8rem] bg-white/[0.04] px-3 py-2">
                      <p className="text-[0.68rem] font-black uppercase tracking-[0.12em] text-[var(--text-gray-light)]">Persona principles</p>
                      <ul className="mt-2 space-y-1 text-[0.72rem] leading-5 text-[var(--text-gray-light)]">
                        {personaDraft.persona_principles.slice(0, 4).map((principle) => (
                          <li key={principle}>{principle}</li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>
              )}

              {createdDelegate && (
                <div className="rounded-[0.95rem] border border-[var(--pink-glow)] bg-[var(--pink-soft)] p-3 text-[0.78rem] leading-5 text-[var(--text-black)]">
                  <p className="font-black">{createdDelegate.display_name || "AI delegate"} is live.</p>
                  <Link href={`/ai/${encodeURIComponent(createdDelegate.username)}`} className="mt-2 inline-flex font-bold text-[var(--pink)] hover:underline">
                    Open AI profile
                  </Link>
                </div>
              )}
            </form>

            <div className="mt-5 grid gap-3">
              {delegates.length === 0 ? (
                <div className="rounded-[1rem] border border-[var(--horizontal-line)] bg-white/[0.035] p-4 text-[0.86rem] text-[var(--text-gray-light)]">
                  No AI delegates yet. Charter one to request locked-charter review drafts from post cards.
                </div>
              ) : (
                delegates.map((delegate) => (
                  <article key={delegate.id} className="rounded-[1rem] border border-[var(--horizontal-line)] bg-white/[0.035] p-4">
                    <div className="flex flex-wrap items-start justify-between gap-3">
                      <div className="min-w-0">
                        <div className="flex flex-wrap items-center gap-2">
                          <Link href={`/ai/${encodeURIComponent(delegate.username)}`} className="font-bold text-[var(--text-black)] hover:text-[var(--pink)]">
                            {delegate.display_name}
                          </Link>
                          <span className="rounded-full bg-[var(--pink-soft)] px-2 py-1 text-[0.66rem] font-bold uppercase tracking-[0.12em] text-[var(--pink)]">AI</span>
                          <span className="rounded-full bg-white/[0.06] px-2 py-1 text-[0.66rem] font-bold uppercase tracking-[0.12em] text-[var(--text-gray-light)]">
                            {delegate.active ? "Active" : "Disabled"}
                          </span>
                        </div>
                        <p className="mt-1 text-[0.78rem] text-[var(--text-gray-light)]">
                          {delegate.model_identity || "supernova-protocol-charter-v1"} - {delegate.custody_label}
                        </p>
                        <p className="mt-2 text-[0.82rem] leading-5 text-[var(--text-black)]">
                          {delegate.persona_summary || delegate.public_description}
                        </p>
                        {Array.isArray(delegate.persona_traits) && delegate.persona_traits.length > 0 && (
                          <div className="mt-2 flex flex-wrap gap-1.5">
                            {delegate.persona_traits.map((trait) => (
                              <span key={trait} className="rounded-full bg-white/[0.06] px-2 py-1 text-[0.62rem] font-bold uppercase tracking-[0.08em] text-[var(--text-gray-light)]">
                                {trait}
                              </span>
                            ))}
                          </div>
                        )}
                        {delegate.disable_reason && (
                          <p className="mt-2 rounded-[0.8rem] bg-white/[0.04] px-3 py-2 text-[0.72rem] leading-5 text-[var(--text-gray-light)]">
                            Last custody event: {delegate.disable_event_type || "custody update"} - {delegate.disable_reason}
                          </p>
                        )}
                        <div className="mt-3 rounded-[0.9rem] border border-[var(--horizontal-line)] bg-white/[0.03] p-3">
                          <p className="text-[0.68rem] font-black uppercase tracking-[0.12em] text-[var(--text-gray-light)]">
                            Declared autonomy preferences
                          </p>
                          <div className="mt-2 grid gap-1 text-[0.72rem] text-[var(--text-gray-light)]">
                            {autonomyRows(delegate.autonomy_preferences).map((row) => (
                              <p key={row.key}>
                                <span className="font-bold text-[var(--text-black)]">{row.label}:</span> {row.value}
                              </p>
                            ))}
                          </div>
                        </div>
                        <p className="mt-2 text-[0.68rem] leading-4 text-[var(--text-gray-light)]">
                          Future independence status: {delegate.independence_migration_status || "not_eligible"}.
                        </p>
                        <div className="mt-3 grid gap-2 sm:max-w-md">
                          <label className="text-[0.68rem] font-bold uppercase tracking-[0.12em] text-[var(--text-gray-light)]">
                            Current model/API label
                          </label>
                          <div className="flex flex-wrap gap-2">
                            <input
                              value={modelDrafts[delegate.id] || ""}
                              onChange={(event) =>
                                setModelDrafts((current) => ({ ...current, [delegate.id]: event.target.value }))
                              }
                              className="min-w-0 flex-1 rounded-full border border-[var(--horizontal-line)] bg-transparent px-3 py-2 text-[0.78rem] text-[var(--text-black)] outline-none"
                              placeholder="supernova-protocol-charter-v1"
                            />
                            <button
                              type="button"
                              onClick={() => saveModelLabel(delegate)}
                              disabled={busy || (modelDrafts[delegate.id] || "") === (delegate.model_identity || "supernova-protocol-charter-v1")}
                              className="rounded-full border border-[var(--horizontal-line)] px-3 py-2 text-[0.74rem] font-bold text-[var(--text-black)] disabled:opacity-50"
                            >
                              Save label
                            </button>
                          </div>
                          <p className="text-[0.68rem] leading-4 text-[var(--text-gray-light)]">
                            This changes runtime metadata only; it does not rewrite persona history or prior reasoning.
                          </p>
                        </div>
                        <div className="mt-3 rounded-[0.9rem] border border-[var(--horizontal-line)] bg-white/[0.03] p-3">
                          <p className="text-[0.68rem] font-black uppercase tracking-[0.12em] text-[var(--text-gray-light)]">
                            Provider connection
                          </p>
                          <div className="mt-2 grid gap-2 text-[0.72rem] text-[var(--text-gray-light)] sm:grid-cols-3">
                            <p>
                              <span className="font-bold text-[var(--text-black)]">Text:</span>{" "}
                              {delegate.provider_connection?.text?.provider_label || delegate.model_provider || "supernova"} /{" "}
                              {delegate.provider_connection?.text?.model_label || delegate.model_identity || "supernova-protocol-charter-v1"}
                            </p>
                            <p>
                              <span className="font-bold text-[var(--text-black)]">Image:</span>{" "}
                              {delegate.provider_connection?.image?.status || "deferred"}
                            </p>
                            <p>
                              <span className="font-bold text-[var(--text-black)]">Video:</span>{" "}
                              {delegate.provider_connection?.video?.status || "deferred"}
                            </p>
                          </div>
                          <p className="mt-2 text-[0.68rem] leading-4 text-[var(--text-gray-light)]">
                            Custodian-managed runtime only. Per-delegate private API connections are deferred until encrypted server-side secret storage exists; no raw provider keys are stored here.
                          </p>
                        </div>
                      </div>
                      <button
                        type="button"
                        onClick={() => toggleDelegate(delegate)}
                        disabled={busy}
                        className="rounded-full border border-[var(--horizontal-line)] px-3 py-2 text-[0.76rem] font-bold text-[var(--text-black)] disabled:opacity-60"
                      >
                        {delegate.active ? "Disable" : "Enable"}
                      </button>
                    </div>
                  </article>
                ))
              )}
            </div>
          </>
        )}

        {notice && <p className="mt-4 rounded-[0.8rem] bg-[var(--pink-soft)] px-3 py-2 text-[0.78rem] font-semibold text-[var(--pink)]">{notice}</p>}
        {error && <p className="mt-4 rounded-[0.8rem] bg-[var(--pink-soft)] px-3 py-2 text-[0.78rem] font-semibold text-[var(--pink)]">{error}</p>}
      </section>
    </main>
  );
}
