"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import Link from "next/link";
import {
  IoBarChartOutline,
  IoCheckmark,
  IoClose,
  IoChatbubbleEllipsesOutline,
  IoDocumentTextOutline,
  IoImageOutline,
  IoSparklesOutline,
  IoVideocamOutline,
} from "react-icons/io5";
import { API_BASE_URL } from "@/utils/apiBase";
import {
  authHeaders,
  formatBackendAuthErrorMessage,
  requireBackendAuthSession,
} from "@/utils/authSession";
import { useUser } from "@/content/profile/UserContext";
import AiDelegatePicker from "./AiDelegatePicker";

function compactHash(value) {
  if (!value) return "";
  const text = String(value);
  return text.length > 14 ? `${text.slice(0, 7)}...${text.slice(-5)}` : text;
}

function generationSourceLabel(value) {
  const labels = {
    openai: "Generated by server AI model",
    deterministic_fallback_no_key: "Fallback draft - backend AI key not configured",
    fallback_after_model_error: "Fallback draft - model request failed",
  };
  return labels[value] || value || "";
}

function mediaIndicators(target = {}) {
  const media = target.media || {};
  return [
    media.image || media.images?.length ? "image present" : "",
    media.video ? "video present" : "",
    media.file || media.pdf || media.link ? "file/link present" : "",
  ].filter(Boolean);
}

function selectedDelegatePayload(delegate = {}) {
  if (!delegate?.id) return { ai_actor_username: delegate?.username };
  return { ai_actor_id: Number(delegate.id) };
}

function delegatePublishName(summary = {}, fallbackDelegate = {}) {
  return (
    summary.ai_actor_display_name ||
    summary.display_name ||
    fallbackDelegate.display_name ||
    summary.ai_actor_username ||
    fallbackDelegate.username ||
    "AI delegate"
  );
}

export default function AiDelegateActionModal({
  open,
  mode = "review",
  target = {},
  composerContext = {},
  initialFocus = "",
  onClose,
  onApproved,
  onCanceled,
}) {
  const { userData, defaultAvatar } = useUser();
  const [mounted, setMounted] = useState(false);
  const [delegates, setDelegates] = useState([]);
  const [loadingDelegates, setLoadingDelegates] = useState(false);
  const [selectedDelegateId, setSelectedDelegateId] = useState("");
  const [focus, setFocus] = useState("");
  const [draftAction, setDraftAction] = useState(null);
  const [busy, setBusy] = useState(false);
  const [reviewBusy, setReviewBusy] = useState("");
  const [notice, setNotice] = useState("");
  const [error, setError] = useState("");
  const [createHandoffOpen, setCreateHandoffOpen] = useState(false);
  const [composerDraftMode, setComposerDraftMode] = useState("text");

  useEffect(() => setMounted(true), []);

  const activeDelegates = useMemo(
    () => (Array.isArray(delegates) ? delegates.filter((delegate) => delegate?.active) : []),
    [delegates]
  );
  const disabledDelegateCount = Math.max(0, (Array.isArray(delegates) ? delegates.length : 0) - activeDelegates.length);
  const selectedDelegate = useMemo(() => {
    if (!activeDelegates.length) return null;
    return (
      activeDelegates.find((delegate) => String(delegate.id || "") === String(selectedDelegateId || "")) ||
      activeDelegates[0]
    );
  }, [activeDelegates, selectedDelegateId]);

  const modeConfig = {
    review: {
      title: draftAction ? "Review ready" : "AI delegate review",
      eyebrow: "AI delegate review",
      description: "",
      button: "Review",
      endpoint: `${API_BASE_URL}/connector/actions/draft-ai-delegate-review`,
      approveEndpoint: (id) => `${API_BASE_URL}/connector/actions/${id}/approve-ai-review`,
      draftType: "draft_ai_review",
      Icon: IoSparklesOutline,
    },
    comment: {
      title: draftAction ? "Comment ready" : "AI comment",
      eyebrow: "AI-authored comment",
      description: "",
      button: "Comment",
      endpoint: `${API_BASE_URL}/connector/actions/draft-ai-delegate-comment`,
      approveEndpoint: (id) => `${API_BASE_URL}/connector/actions/${id}/approve-ai-comment`,
      draftType: "draft_ai_comment",
      Icon: IoChatbubbleEllipsesOutline,
    },
    ai_post: {
      title: draftAction ? "AI post ready" : "AI post",
      eyebrow: "AI delegate post",
      description: "",
      button: "Post",
      endpoint: `${API_BASE_URL}/connector/actions/draft-ai-delegate-post`,
      approveEndpoint: (id) => `${API_BASE_URL}/connector/actions/${id}/approve-ai-post`,
      draftType: "draft_ai_post",
      Icon: IoSparklesOutline,
    },
  }[mode] || {};

  const summary = draftAction?.draft_payload || {};
  const isReview = mode === "review";
  const isComment = mode === "comment";
  const isAiPost = mode === "ai_post";
  const canGenerate = Boolean(
    userData?.name &&
      selectedDelegate &&
      ((target?.id && (isReview || isComment)) || isAiPost)
  );
  const indicators = mediaIndicators(target);
  const composerImageAvailable = Boolean(
    Number(composerContext.image_count || 0) > 0 ||
      (Array.isArray(composerContext.image_files) && composerContext.image_files.length > 0) ||
      (Array.isArray(composerContext.image_data_urls) && composerContext.image_data_urls.length > 0)
  );

  useEffect(() => {
    if (!open) return;
    setDraftAction(null);
    setNotice("");
    setError("");
    setFocus(initialFocus || "");
    setComposerDraftMode("text");
    setCreateHandoffOpen(false);
  }, [initialFocus, open, mode, target?.id]);

  const loadDelegates = useCallback(
    async (signal) => {
      setLoadingDelegates(true);
      setError("");
      try {
        const response = await fetch(`${API_BASE_URL}/ai/delegates`, {
          headers: authHeaders(),
          signal,
        });
        const payload = await response.json().catch(() => ({}));
        if (!response.ok) throw new Error(payload?.detail || "Unable to load AI delegates.");
        const nextDelegates = Array.isArray(payload.delegates) ? payload.delegates : [];
        setDelegates(nextDelegates);
        const firstActive = nextDelegates.find((delegate) => delegate?.active);
        setSelectedDelegateId((current) => current || (firstActive?.id ? String(firstActive.id) : ""));
      } catch (err) {
        if (err?.name !== "AbortError") {
          setDelegates([]);
          setError(formatBackendAuthErrorMessage(err, "Unable to load AI delegates."));
        }
      } finally {
        if (!signal?.aborted) setLoadingDelegates(false);
      }
    },
    []
  );

  useEffect(() => {
    if (!open || !userData?.name) return undefined;
    const controller = new AbortController();
    loadDelegates(controller.signal);
    return () => controller.abort();
  }, [loadDelegates, open, userData?.name]);

  useEffect(() => {
    if (!open) return undefined;
    const onKeyDown = (event) => {
      if (event.key === "Escape") onClose?.();
    };
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [onClose, open]);

  const openAccount = () => {
    window.dispatchEvent(new CustomEvent("supernova:open-account", { detail: { mode: "create" } }));
    onClose?.();
  };

  const cleanError = (detail, fallback) => {
    const message = formatBackendAuthErrorMessage(detail, fallback);
    if (/bearer token|authorization|authenticated|sign in/i.test(message)) {
      return "Sign in as the delegate custodian.";
    }
    if (/Only the delegate custodian|custody no longer matches/i.test(message)) {
      return "Sign in as the delegate custodian.";
    }
    if (/ai_actor_id|AI delegate not found/i.test(message)) {
      return "Choose one of your active AI delegates.";
    }
    if (/AI delegate is disabled/i.test(message)) return "This AI delegate is disabled for future actions.";
    if (/proposal.*not found|unknown proposal/i.test(message)) return "That post is no longer available.";
    return message;
  };

  const readComposerImageDataUrls = async () => {
    const files = Array.from(composerContext.image_files || []).slice(0, 2);
    const existing = Array.isArray(composerContext.image_data_urls) ? composerContext.image_data_urls.slice(0, 2) : [];
    if (!files.length) return existing;
    const readers = files.map(
      (file) =>
        new Promise((resolve) => {
          if (!file || !String(file.type || "").startsWith("image/")) {
            resolve("");
            return;
          }
          const reader = new FileReader();
          reader.onload = () => resolve(String(reader.result || ""));
          reader.onerror = () => resolve("");
          reader.readAsDataURL(file);
        })
    );
    const loaded = await Promise.all(readers);
    return [...existing, ...loaded].filter((url) => String(url || "").startsWith("data:image/")).slice(0, 3);
  };

  const generateDraft = async () => {
    if (busy || !canGenerate) return;
    setBusy(true);
    setError("");
    setNotice("");
    setDraftAction(null);
    try {
      requireBackendAuthSession();
      const imageDataUrls = isAiPost && composerDraftMode === "image" ? await readComposerImageDataUrls() : [];
      const effectiveMediaType =
        isAiPost && composerDraftMode === "image"
          ? "image"
          : isAiPost && composerDraftMode === "video"
          ? "video"
          : isAiPost && composerDraftMode === "proposal"
          ? "proposal framing"
          : composerContext.media_type || "";
      const body = isAiPost
        ? {
            username: userData.name,
            ...selectedDelegatePayload(selectedDelegate),
            current_text: composerContext.current_text || target.text || "",
            focus,
            media_type: effectiveMediaType,
            media_label: composerContext.media_label || "",
            image_count: Number(composerContext.image_count || 0),
            image_data_urls: imageDataUrls,
            governance_kind: composerContext.governance_kind || "post",
            decision_level: composerContext.decision_level || "",
            voting_days: composerContext.voting_days || undefined,
          }
        : {
            username: userData.name,
            proposal_id: Number(target.id),
            ...selectedDelegatePayload(selectedDelegate),
          };
      if (isComment) body.instruction = focus;
      const response = await fetch(modeConfig.endpoint, {
        method: "POST",
        headers: authHeaders({ "Content-Type": "application/json" }),
        body: JSON.stringify(body),
      });
      const payload = await response.json().catch(() => ({}));
      if (!response.ok) throw new Error(cleanError(payload?.detail, "Unable to generate AI draft."));
      setDraftAction({
        id: payload?.action_proposal?.id,
        action_type: payload?.action_proposal?.action_type || modeConfig.draftType,
        draft_payload: payload?.summary || {},
      });
      setNotice(
        isAiPost
          ? "AI post ready. Approve or cancel here."
          : isReview
          ? "Review ready. Approve or cancel here."
          : "Comment ready. Approve or cancel here."
      );
    } catch (err) {
      setError(cleanError(err, "Unable to generate AI draft."));
    } finally {
      setBusy(false);
    }
  };

  const reviewDraft = async (action) => {
    if (!draftAction?.id || reviewBusy) return;
    setReviewBusy(action);
    setError("");
    setNotice("");
    try {
      requireBackendAuthSession();
      const actorName = delegatePublishName(summary, selectedDelegate);
      const endpoint =
        action === "approve"
          ? modeConfig.approveEndpoint(draftAction.id)
          : `${API_BASE_URL}/connector/actions/${draftAction.id}/cancel`;
      const response = await fetch(endpoint, {
        method: "POST",
        headers: authHeaders({ "Content-Type": "application/json" }),
      });
      const payload = await response.json().catch(() => ({}));
      if (!response.ok) {
        throw new Error(formatBackendAuthErrorMessage(payload?.detail, "Unable to update AI draft."));
      }
      if (action === "approve") {
        setNotice(`Published as ${actorName}.`);
        onApproved?.(payload, draftAction);
      } else {
        setNotice("Canceled - nothing published.");
        onCanceled?.(payload, draftAction);
      }
      setDraftAction(null);
      window.setTimeout(() => onClose?.(), 650);
    } catch (err) {
      setError(cleanError(err, "Unable to update AI draft."));
    } finally {
      setReviewBusy("");
    }
  };

  if (!open || !mounted) return null;

  const Icon = modeConfig.Icon || IoSparklesOutline;
  const showHeaderTitle = Boolean(draftAction);
  const createDelegateCard = (
    <div className="ai-delegate-create-card mt-4 rounded-[1rem] border border-[var(--horizontal-line)] bg-white/[0.045] p-3">
      <p className="text-[0.88rem] font-black text-[var(--text-black)]">Create an AI delegate</p>
      <p className="mt-1 text-[0.76rem] leading-5 text-[var(--text-gray-light)]">
        AI Genesis creates a visible delegate with a call-sign, traits, and a locked persona. Return here and refresh the picker.
      </p>
      <div className="mt-3 flex flex-wrap gap-2">
        <Link href="/settings/ai-delegates" onClick={onClose} className="ai-delegate-primary inline-flex rounded-full px-3 py-2 text-[0.74rem] font-black">
          Create AI delegate
        </Link>
        <button
          type="button"
          onClick={() => loadDelegates()}
          className="ai-delegate-secondary rounded-full px-3 py-2 text-[0.74rem] font-black"
        >
          Refresh delegates
        </button>
      </div>
    </div>
  );

  return createPortal(
    <div
      className="ai-delegate-modal-backdrop"
      role="dialog"
      aria-modal="true"
      aria-labelledby="ai-delegate-modal-title"
      onMouseDown={(event) => {
        if (event.target === event.currentTarget) onClose?.();
      }}
    >
      <section className="ai-delegate-modal-card ai-delegate-modal-shell-compact">
        <div className="flex items-start justify-between gap-3">
          <div className="min-w-0">
            <p className="flex items-center gap-2 text-[0.68rem] font-black uppercase tracking-[0.16em] text-[var(--pink)]">
              <Icon className="text-[0.95rem]" />
              {modeConfig.eyebrow}
            </p>
            <h2
              id="ai-delegate-modal-title"
              className={showHeaderTitle ? "mt-1 text-[1.05rem] font-black text-[var(--text-black)]" : "sr-only"}
            >
              {modeConfig.title}
            </h2>
            {modeConfig.description && (
              <p className="mt-1 text-[0.76rem] leading-5 text-[var(--text-gray-light)]">{modeConfig.description}</p>
            )}
          </div>
          <button
            type="button"
            onClick={onClose}
            className="ai-delegate-icon-button"
            aria-label="Close AI delegate action"
          >
            <IoClose />
          </button>
        </div>

        {!userData?.name ? (
          <div className="mt-4 rounded-[1rem] border border-[var(--horizontal-line)] bg-white/[0.045] p-4">
            <p className="text-[0.9rem] font-bold text-[var(--text-black)]">Sign in to use AI delegates.</p>
            <p className="mt-1 text-[0.78rem] leading-5 text-[var(--text-gray-light)]">
              AI delegates review, comment, and draft from their own persona. Publication requires your approval.
            </p>
            <button type="button" onClick={openAccount} className="ai-delegate-primary mt-4 rounded-full px-4 py-2 text-[0.78rem] font-black">
              Sign in
            </button>
          </div>
        ) : loadingDelegates ? (
          <div className="mt-4 rounded-[1rem] border border-[var(--horizontal-line)] bg-white/[0.045] p-4 text-[0.82rem] font-bold text-[var(--text-gray-light)]">
            Loading AI delegates...
          </div>
        ) : activeDelegates.length === 0 ? (
          <div className="mt-4 rounded-[1rem] border border-[var(--horizontal-line)] bg-white/[0.045] p-4">
            <p className="text-[0.9rem] font-bold text-[var(--text-black)]">Create an AI delegate first</p>
            <p className="mt-1 text-[0.78rem] leading-5 text-[var(--text-gray-light)]">
              AI delegates review, comment, and draft from their own persona. Publication requires your approval.
            </p>
            {createDelegateCard}
          </div>
        ) : (
          <>
            {!isAiPost && (
              <div className="ai-delegate-context-compact mt-3 rounded-[1rem] border border-[var(--horizontal-line)] bg-white/[0.045] p-3">
                <p className="text-[0.68rem] font-black uppercase tracking-[0.14em] text-[var(--text-gray-light)]">Post context</p>
                <p className="mt-1 line-clamp-1 text-[0.9rem] font-bold text-[var(--text-black)]">{target.title || "Selected post"}</p>
                {target.author && (
                  <p className="mt-0.5 text-[0.68rem] font-semibold text-[var(--text-gray-light)]">
                    @{target.author}{target.species ? ` - ${target.species}` : ""}
                  </p>
                )}
                <p className="mt-1 line-clamp-2 text-[0.76rem] leading-5 text-[var(--text-gray-light)]">{target.text || "No post text available."}</p>
                {indicators.length > 0 && (
                  <div className="mt-2 flex flex-wrap gap-1.5 text-[0.64rem] font-bold uppercase tracking-[0.1em] text-[var(--text-gray-light)]">
                    {indicators.map((indicator) => (
                      <span key={indicator} className="rounded-full bg-white/[0.06] px-2 py-1">
                        {indicator}
                      </span>
                    ))}
                  </div>
                )}
                {target.text && String(target.text).length > 180 && (
                  <details className="mt-2 text-[0.72rem] text-[var(--text-gray-light)]">
                    <summary className="cursor-pointer font-bold text-[var(--pink)]">More context</summary>
                    <p className="mt-1 max-h-24 overflow-y-auto leading-5">{target.text}</p>
                  </details>
                )}
              </div>
            )}

            <div className="mt-3">
              <div className="ai-delegate-picker-line">
                <div className="min-w-0 flex-1">
                  <AiDelegatePicker
                    delegates={activeDelegates}
                    value={selectedDelegateId || String(selectedDelegate?.id || "")}
                    onChange={(nextId) => {
                      setSelectedDelegateId(nextId);
                      setDraftAction(null);
                      setNotice("");
                    }}
                    defaultAvatar={defaultAvatar}
                    disabledCount={disabledDelegateCount}
                    onCreateDelegate={() => setCreateHandoffOpen((value) => !value)}
                  />
                </div>
                {!draftAction && (
                  <button
                    type="button"
                    onClick={generateDraft}
                    disabled={busy || !canGenerate}
                    className="ai-delegate-generate-icon disabled:opacity-55"
                    aria-label={busy ? "Generating AI draft" : modeConfig.button}
                    title={busy ? "Generating" : modeConfig.button}
                  >
                    <Icon />
                  </button>
                )}
              </div>
              {createHandoffOpen && createDelegateCard}
            </div>

            {(isComment || isAiPost) && !draftAction && (
              <label className="mt-4 block text-[0.68rem] font-black uppercase tracking-[0.14em] text-[var(--text-gray-light)]">
                {isComment ? "Focus" : "Post focus"}
                <input
                  value={focus}
                  onChange={(event) => setFocus(event.target.value.slice(0, 240))}
                  placeholder={isComment ? "What should the AI consider?" : "What should this AI post consider?"}
                  className="ai-delegate-select mt-2 w-full rounded-[0.95rem] px-3 py-2.5 text-[0.84rem] normal-case tracking-normal"
                />
              </label>
            )}

            {isAiPost && !draftAction ? (
              <div className="mt-3 flex flex-wrap gap-2" aria-label="AI post context modes">
                <button
                  type="button"
                  onClick={() => setComposerDraftMode("text")}
                  className={`ai-delegate-mode-icon ${composerDraftMode === "text" ? "is-active" : ""}`}
                  title="Text"
                  aria-label="Use text context"
                  aria-pressed={composerDraftMode === "text"}
                >
                  <IoDocumentTextOutline />
                </button>
                <button
                  type="button"
                  onClick={() => setComposerDraftMode("proposal")}
                  className={`ai-delegate-mode-icon ${composerDraftMode === "proposal" ? "is-active" : ""}`}
                  title="Proposal framing"
                  aria-label="Use proposal framing"
                  aria-pressed={composerDraftMode === "proposal"}
                >
                  <IoBarChartOutline />
                </button>
                <button
                  type="button"
                  onClick={() => setComposerDraftMode("image")}
                  disabled={!composerImageAvailable}
                  className={`ai-delegate-mode-icon ${composerDraftMode === "image" ? "is-active" : ""}`}
                  title={composerImageAvailable ? "Use image context" : "Attach an image first"}
                  aria-label="Use image context"
                  aria-pressed={composerDraftMode === "image"}
                >
                  <IoImageOutline />
                </button>
                <button
                  type="button"
                  disabled
                  className="ai-delegate-mode-icon is-disabled"
                  title="Video context next"
                  aria-label="Video context next"
                >
                  <IoVideocamOutline />
                </button>
              </div>
            ) : isAiPost && draftAction ? (
              <div className="ai-delegate-preview-card mt-4 rounded-[1rem] p-3">
                <p className="text-[0.68rem] font-black uppercase tracking-[0.14em] text-[var(--pink)]">
                  AI post ready
                </p>
                {(summary.generated_title || summary.title) && (
                  <p className="mt-2 text-[0.88rem] font-black text-[var(--text-black)]">{summary.generated_title || summary.title}</p>
                )}
                <p className="mt-2 max-h-44 overflow-y-auto whitespace-pre-line text-[0.82rem] leading-5 text-[var(--text-black)]">
                  {summary.generated_post_body || summary.body || "AI-authored post generated from the locked charter."}
                </p>
                {(summary.governance_framing || summary.media_caption_guidance) && (
                  <details className="mt-2 text-[0.7rem] leading-5 text-[var(--text-gray-light)]">
                    <summary className="cursor-pointer font-bold text-[var(--pink)]">Draft notes</summary>
                    {summary.governance_framing && <p className="mt-1">{summary.governance_framing}</p>}
                    {summary.media_caption_guidance && <p className="mt-1">{summary.media_caption_guidance}</p>}
                  </details>
                )}
                <div className="mt-3 grid gap-1 text-[0.66rem] leading-4 text-[var(--text-gray-light)] sm:grid-cols-2">
                  <p><span className="font-bold text-[var(--text-black)]">Model:</span> {summary.model_identity || "server/fallback"}</p>
                  <p><span className="font-bold text-[var(--text-black)]">Generation:</span> {generationSourceLabel(summary.generation_source)}</p>
                  {summary.context_hash && <p><span className="font-bold text-[var(--text-black)]">Context:</span> {compactHash(summary.context_hash)}</p>}
                  {summary.content_hash && <p><span className="font-bold text-[var(--text-black)]">Content:</span> {compactHash(summary.content_hash)}</p>}
                </div>
              </div>
            ) : draftAction ? (
              <div className="ai-delegate-preview-card mt-4 rounded-[1rem] p-4">
                <p className="text-[0.68rem] font-black uppercase tracking-[0.14em] text-[var(--pink)]">
                  {isReview ? "Review ready" : "Comment ready"}
                </p>
                {isReview ? (
                  <>
                    <p className="mt-2 text-[0.95rem] font-black text-[var(--text-black)]">
                      Vote intent: {summary.intended_choice || summary.normalized_vote || "review"}
                    </p>
                    <p className="mt-2 text-[0.8rem] leading-5 text-[var(--text-gray-light)]">
                      {summary.reasoning_summary || summary.rationale || "AI reasoning generated from the locked charter."}
                    </p>
                  </>
                ) : (
                  <p className="mt-2 text-[0.84rem] leading-5 text-[var(--text-black)]">
                    {summary.generated_comment || summary.body || "AI-authored comment generated from the locked charter."}
                  </p>
                )}
                <div className="mt-3 grid gap-1 text-[0.66rem] leading-4 text-[var(--text-gray-light)] sm:grid-cols-2">
                  <p><span className="font-bold text-[var(--text-black)]">Model:</span> {summary.model_identity || "server/fallback"}</p>
                  <p><span className="font-bold text-[var(--text-black)]">Generation:</span> {generationSourceLabel(summary.generation_source)}</p>
                  {summary.reasoning_hash && <p><span className="font-bold text-[var(--text-black)]">Reasoning:</span> {compactHash(summary.reasoning_hash)}</p>}
                  {summary.content_hash && <p><span className="font-bold text-[var(--text-black)]">Content:</span> {compactHash(summary.content_hash)}</p>}
                </div>
              </div>
            ) : null}

            <div className="mt-3 rounded-[0.9rem] bg-white/[0.04] px-3 py-2 text-[0.72rem] leading-5 text-[var(--text-gray-light)]">
              <details>
                <summary className="cursor-pointer font-bold text-[var(--pink)]">Safety</summary>
                <p className="mt-1">AI-authored delegate actions are approval-required. You cannot edit official AI reasoning or content before publishing. Server model generation uses backend configuration when available.</p>
              </details>
            </div>
          </>
        )}

        {draftAction && (
          <div className="ai-delegate-action-row mt-4 flex items-center justify-between gap-2">
            <button
              type="button"
              onClick={() => reviewDraft("cancel")}
              disabled={Boolean(reviewBusy)}
              className="ai-delegate-action-icon ai-delegate-action-cancel disabled:opacity-55"
              title="Cancel prevents publication."
              aria-label="Cancel AI draft. Nothing will be published."
            >
              <IoClose />
              <span className="sr-only">{reviewBusy === "cancel" ? "Canceling" : "Cancel"}</span>
            </button>
            <button
              type="button"
              onClick={() => reviewDraft("approve")}
              disabled={Boolean(reviewBusy)}
              className="ai-delegate-action-icon ai-delegate-action-approve disabled:opacity-55"
              title="Approve"
              aria-label="Approve AI draft"
            >
              <IoCheckmark />
              <span className="sr-only">{reviewBusy === "approve" ? "Approving" : "Approve"}</span>
            </button>
          </div>
        )}

        {(notice || error) && (
          <p className={`mt-4 rounded-[0.85rem] px-3 py-2 text-[0.76rem] font-bold ${error ? "ai-delegate-error" : "ai-delegate-notice"}`}>
            {error || notice}
          </p>
        )}
        {draftAction && (
          <button
            type="button"
            onClick={() => {
              window.dispatchEvent(new CustomEvent("supernova:ai-actions-refresh", { detail: { notice: "AI Actions opened." } }));
              onClose?.();
            }}
            className="mt-3 text-[0.72rem] font-bold text-[var(--text-gray-light)] hover:text-[var(--pink)]"
          >
            Open in AI Actions
          </button>
        )}
      </section>
    </div>,
    document.body
  );
}
